pipeline:
  prepare-env:
    image: nullaufeins/build-agent
    commands:
      - echo "export SITE=hack-for-good.de" > pipeline.env
      - cat pipeline.env

  build:
    image: nullaufeins/build-agent
    commands:
      - source ./pipeline.env
      - export "DEST_DIR=$SITE"
      - mv www/ "$DEST_DIR"
      - nix-store --add "$DEST_DIR" --store "ssh-ng://$BUILD_HOST" > store_path

  deploy:
    image: nullaufeins/build-agent
    commands:
      - source ./pipeline.env
      - cat store_path | xargs deploy-website "$SITE"

branches: [ main ]
